name: CleanCSS Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install CleanCSS
      run: npm install -g clean-css-cli

    - name: Set Write Permissions
      run: chmod -R +w css/

    - name: Run CleanCSS
      run: cleancss -o css/bootstrap.min.css css/bootstrap/bootstrap.css

    - uses: actions/upload-artifact@v3
      with:
        name: bootstrap.min.css
        path: css/bootstrap.min.css

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
